base: https://awesome.blades.ninja
favicon: /favicon.svg
title: Awesome Blades
subtitle: Awesome list of Blades of any kind 🥷
author:
  name: Anton Staroverov
brand: <big><big><a href="/" class="dark-auto"><span><em>Awe</em>some</span> <i>🥷</i></span></a></big></big>
header_links:
  - title: '<span class="faded opt">|</span>'
  - url: https://github.com/anyblades/awesome-blades
    title: <i class="fa-brands fa-github"></i>
  - url: https://x.com/any_blades
    title: <i class="fa-brands fa-x-twitter"></i>
